services:
  ultradex_web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ultradex_web
      POSTGRES_PASSWORD: ultradex_web
      POSTGRES_DB: ultradex_web
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ultradex_web"]
      interval: 5s
      retries: 5
      timeout: 3s