# fly.toml app configuration file generated for ultradex-web on 2025-01-30T16:07:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ultradex-web'
primary_region = 'sin'

[build]

[env]
  DATABASE_URL = "postgres://ultradex_web:ultradex_web@localhost:5432/ultradex_web?sslmode=disable"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
